-- Supabase SQL Schema for RocketGifti Bot

-- 1. users
CREATE TABLE IF NOT EXISTS users (
    telegram_id BIGINT PRIMARY KEY,
    username TEXT,
    phone TEXT,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. products
CREATE TABLE IF NOT EXISTS products (
    goods_code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    discount_price INTEGER,
    image_url TEXT,
    image_url_big TEXT,
    brand_code TEXT,
    brand_name TEXT,
    category TEXT,
    goods_state_cd TEXT DEFAULT 'SALE',
    affiliate TEXT,
    limit_day INTEGER DEFAULT 30,
    mms_goods_img TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. cart_items
CREATE TABLE IF NOT EXISTS cart_items (
    telegram_id BIGINT NOT NULL,
    goods_code TEXT NOT NULL,
    qty INTEGER NOT NULL,
    PRIMARY KEY (telegram_id, goods_code)
);

-- 4. orders
CREATE TABLE IF NOT EXISTS orders (
    order_id TEXT PRIMARY KEY,
    admin_telegram_id BIGINT NOT NULL,
    total_price INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    payment_deadline_at TIMESTAMP,
    note TEXT
);

-- 5. order_items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    goods_code TEXT NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    qty INTEGER NOT NULL
);

-- 6. order_winners
CREATE TABLE IF NOT EXISTS order_winners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    winner_username TEXT NOT NULL,
    winner_telegram_id BIGINT,
    winner_phone TEXT,
    send_status TEXT NOT NULL,
    tr_id TEXT,
    response_code TEXT,
    response_message TEXT,
    coupon_pin TEXT,
    coupon_img_url TEXT,
    order_no TEXT
);

-- 7. events (Phase 3: B2B Agency)
CREATE TABLE IF NOT EXISTS events (
    event_id TEXT PRIMARY KEY,
    admin_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    goods_code TEXT NOT NULL,
    winner_count INTEGER NOT NULL,
    draw_type TEXT DEFAULT 'RANDOM',
    status TEXT DEFAULT 'OPEN',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. event_participants (Phase 3: B2B Agency)
CREATE TABLE IF NOT EXISTS event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    telegram_id BIGINT NOT NULL,
    username TEXT,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quiz_answer TEXT,
    is_winner BOOLEAN DEFAULT FALSE,
    send_status TEXT DEFAULT 'READY',
    tr_id TEXT,
    coupon_pin TEXT,
    coupon_img_url TEXT,
    UNIQUE(event_id, telegram_id)
);
